### ISSUE TITLE
Metadata about the "layers" needs a place

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/OGC-API-Maps#13]
In WMS there is all this metadata for each layer:

Name
Title 
Abstract
KeywordList  
Style   
CRS  
EX_GeographicBoundingBox  
BoundingBox  
Dimension  
Attribution  
AuthorityURL 
Identifier 
MetadataURL 
DataURL 
FeatureListURL  
MinScaleDenominator, 
MaxScaleDenominator 
queryable  
cascaded  
opaque  
noSubsets  
fixedWidth 
fixedHeight

Where is this metadata in the new "model"?
We need to extent /collections/collectionId and .../coverages/coverageId

**Comment by pomakis** [comment]
If my understanding of the new model is correct, none of this metadata is relevant any more.

**Comment by joanma747** [comment]
The necessary things has found a place somehow. We may need a final review of this when the standards is finalize.

**Comment by joanma747** [comment]
Discussion continues in issue #69
