### ISSUE TITLE
Inconsistent bounds/extent definitions

### ISSUE THREAD

**Issue by jackrabbit128** [opengeospatial/OGC-API-Maps#14]
Looking at the [Map Tiles API](https://app.swaggerhub.com/apis/joanma747/opf-map-tiles-api/1.0.0), we see bounding boxes and extents defined in different ways.

In the [description of a collection](https://app.swaggerhub.com/apis/joanma747/opf-map-tiles-api/1.0.0#/Capabilities/describeCollection), we see
```
  "extent": {
    "spatial": {
      "bbox": [
        [
          -180,
          -90,
          180,
          90
        ]
      ],
      "crs": "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
    },
    "temporal": {
      "interval": [
        [
          "2011-11-11T12:22:11Z",
          null
        ]
      ],
      "trs": "http://www.opengis.net/def/uom/ISO-8601/0/Gregorian"
    }
  }
```

However, in the [description of tile matrix set](https://app.swaggerhub.com/apis/joanma747/opf-map-tiles-api/1.0.0#/Capabilities/getTileMatrixSetDescription), we see
```
  "boundingBox": [
    {
      "type": "BoundingBox",
      "crs": "http://www.opengis.net/def/crs/EPSG/0/3857",
      "lowerCorner": [
        -20037508.3427892,
        -20037508.342789
      ],
      "upperCorner": [
        20037508.3427892,
        20037508.3427892
      ]
    }
  ]
```

One would think that it should be possible to have a more uniform way of describing an extent. It certainly seems like this is a very common need for many of the related specifications.

**Comment by joanma747** [comment]
With Clemens we have made "extent" as a "composition" of spatial and temporal so we can use spatial extent or temporal extent.

**Comment by joanma747** [comment]
Both bboxes are imported from different places. One comes from common and the other from tilematrixset. There is very little we could do from this API. This could be addressed in the next revision of the 2D tilematrixset standard.
