### ISSUE TITLE
maps (and tiles) that have buildings and temperature distribution in the city.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/OGC-API-Maps#17]
Buildings are "items" so we use a {collectionId} 
temperature is a coverage so we use {coverageId}

So map?collections=buildings,tepemrature  does not work

What is gona be:

map?data=colletion:buildings,coverage:temperature ??

**Comment by AdamBranscomb** [comment]
For me this is not an issue that needs solving in the specification.  The map is ultimately the client's, not the server's.

If i want coverages data, i make a coverage request. If i want features i make a features request. if i want both i make two requests. It is the client's responsibility to overlay this data appropriately. Surely the whole point of a standard on interoperability is that i don't need to hold all the data for my map on just my server: in your example, I would get by buildings data from a service provided by the Ordnance Survey, and the temperature data from a service provided by the MET office.

**Comment by joanma747** [comment]
Now that coverageIds are collections the problem is solved by itself
