### ISSUE TITLE
Maps and Tiles in their own repositories?

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/OGC-API-Maps#24]
I just read 'We have decided an aggressive path to modularization having 2 cores, one for tiles and another for maps that can be combined as needed' and I think that's a really great move. 

Have we considered putting each 'core' in its own repository? I think it's quite important we present the smallest possible conceptual surface area to potential new users of a specification, and it should help us make sure each 'core' can stand alone. Of course both could reference each other, but I think it would make things simpler to have each as their own repo / standard.

**Comment by ghobona** [comment]
@joanma747 , if the WMS SWG approves, I am also supportive of the separation into two repos.

**Comment by joanma747** [comment]
It is done.
