### ISSUE TITLE
"map" versus "layer"

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/OGC-API-Maps#26]
Throughout the history of OGC web map specifications, the terms "layer" and "map" have been used in a well-defined and consistent way.  A layer is a rasterized styled rendering of a one or more feature sets and/or coverages (i.e., collections), and a map is a visual stack of layers (possibly served from multiple servers, and/or rendered on the client side from vector tiles, etc.) where each layer has a different z-index.

The new OGC API proposals dispose of layers as a named entity.  They still exist and are requestable; there's just no requirement for them to have names any more.  And that's fine. 

Unfortunately, though, the current "OGC API - Maps" proposal uses the term "map" for a layer.  That is, a layer that renders a specific collection in a specific style is requested with /collections/{collectionId}/map/{styleId}?..., and a layer that renders more than one collection is requested with /map?....  Why the change in terminology?  I know there's a concern that that some may confuse the term "layer" with "data layer" (a.k.a., a feature-set or coverage collection), but "data layer" has never been an OGC term, and it's very easy for the OGC specifications to clearly define "layer" as meaning a "presentation layer", i.e., a styled rendering.

I suspect that calling a layer a "map" would lead to years of unnecessary confusion during the transition from the old OGC web services to the new OGC APIs.  Case in point: If a client requests multiple "maps" from one or more servers and overlays them for presentation, what is the resulting overlayed presentation called?  Calling it a "map" would be confusing, because it's actually a stack of "maps".  Sure, one could say that a "map" is hierarchical in nature, and that what's being shown is a "map of maps", but to me that's an unnecessary complication, when the english term "layer" is extraordinarily appropriate to describe the different z-index things of the map.

I propose that that we don't shy away from the term "layer".  The endpoints should be called "layer", and perhaps "OGC API - Maps" should be called "OGC API - Layers"

**Comment by pomakis** [comment]
Okay, I realize that the WMS operation is called GetMap, and that kinda weakens my point.  But it's important to note here that the WMS GetMap operation returns an image of one or more layers (a term that the WMS specifications use liberally), where each layer is a rendering of one or more coverages and/or feature sets.  The new OGC API simplifies this model by limiting requests to one layer at a time.  It's not really a limitation, of course, because the new API allows the client to request a layer of an arbitrary set of collections rather than having to rely on server-defined layers.  So that's my justification for proposing that the new OGC API use the term "layer" despite the WMS operation being called "GetMap".

**Comment by jeffharrison** [comment]
Was this question resolved? If yes, how?

Thanks and Regards,
Jeff

**Comment by joanma747** [comment]
I believe we have accepted the naming convention. "map" expresses a transformation of a collection into a map. "collection" represents the old "layer" but it is closer to the data itself.
