### ISSUE TITLE
Is CRS a path or a query parameter?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/OGC-API-Maps#37]
In WMS there is a CRS parameter that has two roles: it indicates the CRS of the data rendered in the map and the CRS of the 4 coordinated in the bbox.

The immediate  translation of the WMS notations into OGC API maps will be:
/collections/{collectionId}/map/{styleId}?CRS=CRS84&BBOX=4,4,4,4&width=640&height=480
is this what we want?

Considering that CRS has this dual role (CRS of the map as well as CRS of the bbox) it makes sense to consider that the CRS is part of the map creation process (considering the map a a BIG raster that will be latter subset into small pieces all sharing the same CRS)
/collections/{collectionId}/map/{styleId}/[crsId}?BBOX=4,4,4,4&width=640&height=480

In this notation a collection /collections/{collectionId} is transformed into a BIG map by applying an styleId and a crsId.
After that, the map is arbitrarily subset into small images for visualizations. 

So we have two options and we need to decide about with one.

**Comment by pomakis** [comment]
One issue with having {crsId} as a path element is that it's usually a full URI in its own right.  E.g.:

    http://www.opengis.net/def/crs/EPSG/0/3857

Technically this doesn't pose a problem because it would be URL encoded, e.g.:

    http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F3857

But some people might object to having encoded slashes in the path like that.

**Comment by joanma747** [comment]
That is a good point. I forgot about that because I'm still thinking on the old WMS 1.1!!. Having the CRS URL as a query parameter will also result in terrible encoding but I guess that not so terrible.

One way out could be that when the list of CRSs is presented as part of a ...\map path (Map description) a short name is associated to each long URI. But this has also the limitation that every server can give the CRS a different internal name making difficult to interoperate. It will complicate the lives of servers supporting long lists of CRSs.

**Comment by joanma747** [comment]
"crs=" is going to be a query parameter

**Comment by joanma747** [comment]
The change has been applied to the bbox extension.
